### ISSUE TITLE
[EndeavourOS / Arch Linux] Did not work "out of the box" 

### ISSUE THREAD

**Issue by awyxx** [andweeb/presence.nvim#7] opened 2021-04-29 19:56 UTC
Hello, I have installed this plugin with Plug for my Neovim, but for some reason, nothing really happened.
What should I really do? (Linux)

Yes, I am running Neovim 0.5

`
❯ nvim -v
NVIM v0.5.0-dev+1282-gfbe18d9ca
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
`

**Comment by andweeb** [comment] 2021-04-29 20:22
Hi @awyxx! The idea is that you shouldn't have to do anything to get the plugin to work, so thanks for reporting!

A couple questions:
* Is Discord running with Game Activity enabled in your settings? (just making sure!)
* Which Linux distro are you using?
* Are you running into any errors?

In your `.vimrc` you can enable logging with `let g:presence_log_level="debug"` and view the logs with `:messages`.

**Comment by awyxx** [comment] 2021-04-29 20:37
Hi, thanks for answering :)
1. Yes it is enabled.
2. Im using EndeavourOS
3. Not really.. I can open Neovim without any error, it just doesnt do anything.

After adding `let g:presence_log_level="debug"` to my `init.vim`, those are the logs:
`
[presence.nvim] Setting up plugin...
[presence.nvim] Completed plugin setup
[presence.nvim] Getting nvim socket addresses...
[presence.nvim] Custom setup not detected, using defaults
[presence.nvim] Connecting to Discord...
[presence.nvim] Failed to connect to Discord: ENOENT
[presence.nvim] Got nvim socket addresses: {}
[presence.nvim] No other remote nvim instances
`

**Comment by PieroNarciso** [comment] 2021-04-29 20:47
Hi, I am running with the same issue.
All was working out of the box on later neovim builds. Today I updated from 1227-gb518b9076 to 1282-gfbe18d9ca and is not working.
* Game activity is enabled
* I am using Arch lInux
* I can use neovim without problems

**Comment by ashwinkhode** [comment] 2021-04-29 21:49
Hi, I am running with the same issue as well.
I installed the plugin. Restart the neovim. But its not working!

## Expected Behavior
- Discord connected message

## Actual Behavior
- No message at all

`Note: I have set presence_log_level = "debug" but still no message getting printed`

## Environment
- OS: Windows 10 ( Not using WSL )
- Terminal: Alacritty ( xterm-256color )
- Vim: Neovim 0.5.0 ( nightly )
- Discord Game Activity is on but no activity for Neovim is detected :(

**Comment by andweeb** [comment] 2021-04-30 00:38
@awyxx & @PieroNarciso Awesome, I think I found the bug! Could you update your config to point to the `xdg-runtime-dir-fix` branch and update your plugin to see if it fixes your issue?

For `vim-plug` for example you'd do something like `Plug 'andweeb/presence.nvim', { 'branch': 'xdg-runtime-dir-fix' }` and run `:PlugUpdate`.

---

Re: @ashwinkhode Aw man, and I just tested Windows the other day! That sounds like a separate issue, could you open a new issue with a "[Windows]" prefix?

**Comment by PieroNarciso** [comment] 2021-04-30 01:15
> @awyxx & @PieroNarciso Awesome, I think I found the bug! Could you update your config to point to the `xdg-runtime-dir-fix` branch and update your plugin to see if it fixes your issue?
> 
> For `vim-plug` for example you'd do something like `Plug 'andweeb/presence.nvim', { 'branch': 'xdg-runtime-dir-fix' }` and run `:PlugUpdate`.
> 
> Re: @ashwinkhode Aw man, and I just tested Windows the other day! That sounds like a separate issue, could you open a new issue with a "[Windows]" prefix?

It solved the issue for me, now presence is working as intended.

**Comment by StanczakDominik** [comment] 2021-04-30 05:10
I can also confirm the `xdg-runtime-dir-fix` branch fixes the issue for me on Arch :)

**Comment by andweeb** [comment] 2021-04-30 06:04
Nice, thanks for verifying everyone! I've merged in the fix so you should be able to use the default branch in your configs.

If you still run into the same issue despite the latest changes, feel free to re-open this!

**Closed by andweeb** 2021-04-30 06:04 UTC

**Comment by awyxx** [comment] 2021-04-30 13:40
Aye, sorry for commenting again, but it works now for me aswell :) Thanks!
