### ISSUE TITLE
[Bug] Startify gives error "Pipe was closed" and no presence

### ISSUE THREAD

**Issue by jakobkhansen** [andweeb/presence.nvim#18] opened 2021-05-27 13:20 UTC
Hi,

I use the Startify plugin, and whenever I open Neovim into Startify, I get the log error "Pipe was closed". I assume this might be because Startify does not have a proper "filename"/"filetype". I tried digging around in your code to fix this myself, but couldn't figure it out. Would love a fix for this so that I can get presence again :). Btw, I think this worked previously, and only recently stopped working.

**Comment by andweeb** [comment] 2021-05-27 17:31
Hmm that's interesting, that error basically means the plugin either failed to connect or authorize with Discord. Looks like I can replicate it locally, for some reason the Startify plugin does something that messes up with the initial handshaking with Discord:
```
[presence.nvim] Setting up plugin...
[presence.nvim] Using runtime path: /var/folders/mm/8qfxwcdn29s8d_rzmj7bqxb40000gn/T/
[presence.nvim] Completed plugin setup
[presence.nvim] Getting nvim socket addresses...
[presence.nvim] Custom setup not detected, using defaults
[presence.nvim] Connecting to Discord...
[presence.nvim] Connected to Discord
[presence.nvim] Authorizing with Discord...
[presence.nvim] Authorizing with Discord...
[presence.nvim] Wrote message to pipe
[presence.nvim] Wrote message to pipe
[presence.nvim] Got nvim socket addresses: {}
[presence.nvim] No other remote nvim instances
[presence.nvim] Already authorized with Discord
[presence.nvim] Current buffer not named, skipping...
[presence.nvim] Pipe was closed
```
The authorize call is sent twice, so I'm suspecting there may be race condition caused by Startify somehow.

I don't think I see a workaround for this at the moment, sorry! The authorization logic is a little involved, but I'd take a look at `Presence.discord_event` wrapper function to see if there's anything in there that causes a race condition with authorizing.

I'm a bit busy this week so I'll investigate and follow up with you sometime next week unless I find some time before then :) And of course let me know if you uncover any more info, thanks for reporting!

**Comment by andweeb** [comment] 2021-06-01 02:15
Hi @jakobkhansen! Looks like my suspicion was correct, multiple authorize calls made in tandem somehow trips up Discord and invalidates the IPC connection for the rest of the session, and (with startify) two authorization attempts occur with the initial unnamed buffer and subsequent startify start screen, resulting in that `Pipe was closed` error.

I've just pushed the fix so Discord Rich Presence should start working again with startify after you update. I've tested it out and it seems to be working fine so I'll close this out, but let me know if you're still having issues. Thanks for reporting this! :)

**Closed by andweeb** 2021-06-01 02:15 UTC
